### ISSUE TITLE
The Auto Mega-Issue 2: Electric Boogaloo

### ISSUE THREAD

**Issue by octylFractal** [Team5818/Rogue-Cephalopod-FRC2017#1]
- [x] Raise the collector arm to a set angle -- assigned to @Albert-Miao -- https://github.com/kenzierocks/Arronax-FRC2017/tree/feature/raiseArmCollectorCmd
- [x] Roll the collector rollers until the current spikes -- assigned to @kenzierocks -- #2
- [x] Roll the collector rollers until the laser sensor is triggered -- assigned to @kenzierocks -- #2
- [x] Roll the climber winch until the current spikes -- assigned to @kenzierocks
- [x] Single gear auto -- assigned to  `null`
- [x] Multi-gear auto -- assigned to  `null`
- [x] Far-peg single gear auto -- assigned to  `null`
- [x] Do Nothing (This is a hard one) -- assigned to @km00700 -- alternatively, see `DoNothing` in #2
- [x] Actuate Gear Piston -- assigned to @Albert-Miao -- https://github.com/kenzierocks/Arronax-FRC2017/tree/feature/DeployGears
- [x] Shift Drive Gears  -- assigned to @JacksonMcLaughlin
